name: Deploy to S3

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSKEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESSKEY_ID }}
          aws-region: ap-south-1   # change if needed

      - name:  Deploy to S3
        run:  aws s3 sync . s3://car-web-12345 --delete
